settings:
  variables:
    entity_tablet: switch.lenovo_tab_m8_screensaver
    entity_browser_mod: media_player.browser_d82d75b5_9ef81ed9a
    translate_unknown: Unknown
    translate_idle: Idle
    translate_home: Home
    translate_not_home: Away
    translate_available: Available
    translate_no_updates: No Updates
    translate_update_available: Update Available
    translate_updates_available: Updates Available