light:
  - platform: group
    name: Keylights
    entities:
      - light.left_light
      - light.right_light

  - platform: group
    name: Office
    entities:
      - light.office_light_lf
      - light.office_light_rb
      - light.office_light_lb
      - light.office_light_rf


homeassistant:
  customize:
    # light.vardagsrum_group:
    #   friendly_name: Belysning
    # light.studio_dator:
    #   friendly_name: Datorlampa
    # light.studio_group:
    #   friendly_name: Taklampor
    # light.sovrum_group:
    #   friendly_name: Sänglampor
    # light.badrum_group:
    #   friendly_name: Badrum
    # light.hall_group:
    #   friendly_name: Hallampor
    # sensor.dimmer_badrum_battery_level:
    #   friendly_name: Dimmer Badrum
    # sensor.dimmer_sovrum_battery_level:
    #   friendly_name: Dimmer Sovrum
    # sensor.sensor_hall_battery:
    #   friendly_name: Sensor Hall
    # sensor.sensor_garderob_battery:
    #   friendly_name: Sensor Garderob
    # sensor.sensor_badrum_battery:
    #   friendly_name: Sensor Badrum
