homeassistant:
  customize:
    person.trent:
      entity_picture: /local/trent.jpg
    device_tracker.trent_s_iphone:
      entity_picture: /local/device_tracker.svg

# person:
#   - name: Matte
#     id: matte
#     device_trackers:
#       - device_tracker.mattias_iphone_unifi
#       - device_tracker.iphone #ios

#   - name: Sanja
#     id: sanja
#     device_trackers:
#       - device_tracker.sanjas_iphone_unifi
#       - device_tracker.sanjas_iphone_13 #ios

mqtt:
  sensor:
    - name: trent_last_changed
      state_topic: homeassistant/persistence/trent
      value_template: >
        {{ value | replace(' ', 'T') }}

    - name: caitlyn_last_changed
      state_topic: homeassistant/persistence/caitlyn
      value_template: >
        {{ value | replace(' ', 'T') }}

automation:
  - alias: person_home
    id: '8423590985012'
    mode: parallel
    trigger:
      platform: state
      entity_id:
        - person.trent
        - person.caitlyn
      from:
        - home
        - not_home
      to:
        - home
        - not_home
    action:
      service: mqtt.publish
      data:
        topic_template: >
          homeassistant/persistence/{{ trigger.to_state.name | lower }}
        payload_template: >
          {{ now() }}
        retain: true
