homeassistant:
  customize:
    switch.lenovo_tab_m8_screensaver:
      friendly_name: Screensaver
      icon: mdi:power-sleep
    number.lenovo_tab_m8_screen_brightness:
      friendly_name: Display
      icon: mdi:tablet
    switch.lenovo_tab_m8_screen:
      friendly_name: Display
      icon: mdi:tablet
    binary_sensor.lenovo_tab_m8_plugged_in:
      friendly_name: Power Supply
      icon: mdi:power-plug
    sensor.lenovo_tab_m8_last_app_start:
      friendly_name: Last Reboot
      icon: mdi:update
    sensor.lenovo_tab_m8_battery:
      friendly_name: Battery

template:
  - sensor:
      - unique_id: fullykiosk_storage
        state: >
          {% set FreeSpace = states('sensor.lenovo_tab_m8_internal_storage_free_space') | float(default=0) %}
          {% set TotalSpace = states('sensor.lenovo_tab_m8_internal_storage_total_space') | float(default=0) %}
          {% if not (FreeSpace == 0.0 or TotalSpace == 0.0) %}
            {{ 100 - (FreeSpace / TotalSpace * 100) | int(default=0) }}
          {% endif %}
        attributes:
          friendly_name: Lagring
          icon: mdi:sd
          unit_of_measurement: "%"

      - unique_id: fullykiosk_memory
        state: >
          {% set FreeMemory = states('sensor.lenovo_tab_m8_free_memory') | float(default=0) %}
          {% set TotalMemory = states('sensor.lenovo_tab_m8_total_memory') | float(default=0) %}
          {% if not (FreeMemory == 0.0 or TotalMemory == 0.0) %}
            {{ 100 - (FreeMemory / TotalMemory * 100) | int(default=0) }}
          {% endif %}
        attributes:
          friendly_name: Memory
          icon: mdi:memory
          unit_of_measurement: "%"

automation:
  # - alias: homeassistant_start
  #   id: '7426848686945'
  #   trigger:
  #     platform: homeassistant
  #     event: start
  #   action:
  #     - service: button.press
  #       target:
  #         entity_id: button.lenovo_tab_m8_load_start_url
  #     - delay:
  #         minutes: 1
  #     - if:
  #         condition: state
  #         entity_id: light.hall
  #         state: 'off'
  #       then:
  #         service: switch.turn_on
  #         target:
  #           entity_id: switch.lenovo_tab_m8_screensaver

  - alias: ios_notify_tablet_unplugged
    id: "3972668118831"
    trigger:
      platform: numeric_state
      entity_id: sensor.lenovo_tab_m8_battery
      below: 50
    action:
      service: notify.all_devices
      data:
        title: Office Tablet unplugged
        message: >
          Battery {{ states(trigger.entity_id) }}%

  # - alias: fullykiosk_screensaver
  #   id: '9452750674803'
  #   mode: restart
  #   trigger:
  #     - platform: state
  #       entity_id: binary_sensor.hall_motion_motion
  #       from: 'off'
  #       to: 'on'
  #     - platform: state
  #       entity_id: light.hall
  #       from: 'on'
  #       to: 'off'
  #   action:
  #     if: >
  #       {{ 'hall_motion_motion' in trigger.entity_id }}
  #     then:
  #       - service: switch.turn_off
  #         target:
  #           entity_id: switch.lenovo_tab_m8_screensaver
  #       - service: number.set_value
  #         target:
  #           entity_id: number.lenovo_tab_m8_screen_brightness
  #         data:
  #           value: >
  #             {% set day_percent = 90 %}
  #             {% set night_percent = 65 %}
  #             {% set day_convert = ((day_percent * 255) / 100) | int %}
  #             {% set night_convert = ((night_percent * 255) / 100) | int %}
  #             {{ iif(is_state('sun.sun', 'above_horizon'), day_convert, night_convert) }}
  #     else:
  #       - service: switch.turn_on
  #         target:
  #           entity_id: switch.lenovo_tab_m8_screensaver
  #       - delay:
  #           minutes: 15
  #       - service: browser_mod.close_popup
  #         data:
  #           browser_id: tablet
